#!/usr/bin/env bash
# Build what actually SHIPS, on the MSRV that is actually DECLARED.
#
# D-010 says the crate builds on 1.65 and the MSRV CI job proved it -- against
# the repo. Consumers do not get the repo. `cargo package` writes its own
# Cargo.lock into the tarball, generated by whatever toolchain publishes, so
# the artifact and the repo can disagree. They did: `linq_rs 0.2.0` packaged a
# lockfile at format v4 against `rust-version = "1.65"`, and
#
#   lock file version `4` was found, but this version of Cargo does not
#   understand this lock file
#
# on 1.75 -- let alone 1.65. Every existing check passed, because not one of
# them looked inside the tarball. See DECISIONS.md D-023.
#
# Usage: msrv-tarball.sh [MSRV]     (default: the rust-version in Cargo.toml)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

MSRV="${1:-$(awk -F'"' '/^rust-version/ {print $2; exit}' Cargo.toml)}"
[ -n "$MSRV" ] || { echo "FAIL: could not read rust-version from Cargo.toml"; exit 1; }
# `rustup run 1.65` resolves to a toolchain named 1.65; installs are 1.65.0.
case "$MSRV" in *.*.*) MSRV_TC="$MSRV" ;; *) MSRV_TC="${MSRV}.0" ;; esac

# v3 is understood by Cargo 1.53+. Anything above that must be justified against
# the declared floor, not against whatever the publisher happens to run.
MAX_LOCKFILE_VERSION=3

echo "=== declared MSRV: ${MSRV} (toolchain ${MSRV_TC}) ==="
rustup toolchain install "$MSRV_TC" --profile minimal >/dev/null 2>&1 || true
rustup run "$MSRV_TC" rustc --version \
  || { echo "FAIL: no ${MSRV_TC} toolchain available"; exit 1; }

# Package the way a publisher does -- with stable, not with the MSRV. Packaging
# on the MSRV would generate a lockfile the MSRV can obviously read, which is
# exactly the tautology that let the defect through.
# `cargo package --workspace` packages `publish = false` members too, even
# though `cargo publish --workspace` correctly skips them. Ask cargo which
# packages actually ship rather than assuming, or this gate reports on an
# artifact no consumer will ever see.
PUBLISHABLE="$(cargo metadata --no-deps --format-version 1 \
  | python3 -c "import json,sys; print(' '.join(p['name'] for p in json.load(sys.stdin)['packages'] if p.get('publish') != []))")"
[ -n "$PUBLISHABLE" ] || { echo "FAIL: no publishable packages found"; exit 1; }
echo "publishable packages: ${PUBLISHABLE}"

echo
echo "=== packaging with stable (as a real publish does) ==="
rustup toolchain install stable --profile minimal >/dev/null 2>&1 || true
pkg_args=(); for p in $PUBLISHABLE; do pkg_args+=(-p "$p"); done
rustup run stable cargo package "${pkg_args[@]}" --allow-dirty 2>&1 | grep -E "Packaged|error"

# Honour CARGO_TARGET_DIR -- globbing a hard-coded `target/` silently reads
# whatever stale .crate files happen to be there when it is set, which is a
# gate that reports on the wrong artifact.
TARGET_DIR="${CARGO_TARGET_DIR:-$ROOT/target}"
PKG_DIR="${TARGET_DIR}/package"
shopt -s nullglob
crates=("${PKG_DIR}"/*.crate)
shopt -u nullglob
[ "${#crates[@]}" -gt 0 ] || { echo "FAIL: no .crate files in ${PKG_DIR}"; exit 1; }
echo "reading tarballs from ${PKG_DIR}"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
for c in "${crates[@]}"; do tar -xzf "$c" -C "$WORK"; done

fail=0
echo
for d in "$WORK"/*/; do
  pkg="$(basename "$d")"
  # Skip anything left over in target/package/ that is not a publishable crate
  # -- stale artifacts there would otherwise be silently graded as if they ship.
  name="$(awk -F'"' '/^name *=/ {print $2; exit}' "${d}Cargo.toml")"
  case " ${PUBLISHABLE} " in *" ${name} "*) ;; *) echo "skipping ${pkg} (not publishable)"; continue ;; esac
  lock="${d}Cargo.lock"
  [ -f "$lock" ] || { echo "FAIL: ${pkg} ships no Cargo.lock"; fail=1; continue; }
  ver="$(awk -F'= *' '/^version *=/ {gsub(/[^0-9]/,"",$2); print $2; exit}' "$lock")"
  echo "=== ${pkg}: lockfile v${ver} ==="
  if [ "${ver:-99}" -gt "$MAX_LOCKFILE_VERSION" ]; then
    echo "FAIL: ${pkg} ships lockfile v${ver}; Cargo ${MSRV} cannot parse above v${MAX_LOCKFILE_VERSION}"
    fail=1
    continue
  fi

  # Both published crates have zero dependencies of any kind (D-024), so every
  # tarball builds fully offline. If this ever needs a `[patch.crates-io]` to
  # get through, a dependency crept back in.

  if (cd "$d" && rustup run "$MSRV_TC" cargo build --lib --offline 2>&1 | tail -3); then
    echo "  builds on ${MSRV_TC}"
  else
    echo "FAIL: ${pkg} does not build on ${MSRV_TC}"
    fail=1
  fi
done

echo
if [ "$fail" -ne 0 ]; then echo "MSRV tarball gate FAILED"; exit 1; fi
echo "PASS: every published tarball builds on ${MSRV_TC}"
