#!/usr/bin/env bash
# Build what actually SHIPS, on the MSRV that is actually DECLARED.
#
# D-010 says the crate builds on 1.65 and the MSRV CI job proved it -- against
# the repo. Consumers do not get the repo. `cargo package` writes its own
# Cargo.lock into the tarball, generated by whatever toolchain publishes, so
# the artifact and the repo can disagree. They did: `linq_rs 0.2.0` packaged a
# lockfile at format v4 against `rust-version = "1.65"`, and
#
#   lock file version `4` was found, but this version of Cargo does not
#   understand this lock file
#
# on 1.75 -- let alone 1.65. Every existing check passed, because not one of
# them looked inside the tarball. See DECISIONS.md D-023.
#
# Usage: msrv-tarball.sh [MSRV]     (default: the rust-version in Cargo.toml)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

MSRV="${1:-$(awk -F'"' '/^rust-version/ {print $2; exit}' Cargo.toml)}"
[ -n "$MSRV" ] || { echo "FAIL: could not read rust-version from Cargo.toml"; exit 1; }
# `rustup run 1.65` resolves to a toolchain named 1.65; installs are 1.65.0.
case "$MSRV" in *.*.*) MSRV_TC="$MSRV" ;; *) MSRV_TC="${MSRV}.0" ;; esac

# v3 is understood by Cargo 1.53+. Anything above that must be justified against
# the declared floor, not against whatever the publisher happens to run.
MAX_LOCKFILE_VERSION=3

echo "=== declared MSRV: ${MSRV} (toolchain ${MSRV_TC}) ==="
rustup toolchain install "$MSRV_TC" --profile minimal >/dev/null 2>&1 || true
rustup run "$MSRV_TC" rustc --version \
  || { echo "FAIL: no ${MSRV_TC} toolchain available"; exit 1; }

# Package the way a publisher does -- with stable, not with the MSRV. Packaging
# on the MSRV would generate a lockfile the MSRV can obviously read, which is
# exactly the tautology that let the defect through.
# `cargo package --workspace` packages `publish = false` members too, even
# though `cargo publish --workspace` correctly skips them. Ask cargo which
# packages actually ship rather than assuming, or this gate reports on an
# artifact no consumer will ever see.
PUBLISHABLE="$(cargo metadata --no-deps --format-version 1 \
  | python3 -c "import json,sys; print(' '.join(p['name'] for p in json.load(sys.stdin)['packages'] if p.get('publish') != []))")"
[ -n "$PUBLISHABLE" ] || { echo "FAIL: no publishable packages found"; exit 1; }
echo "publishable packages: ${PUBLISHABLE}"

echo
echo "=== packaging with stable (as a real publish does) ==="
rustup toolchain install stable --profile minimal >/dev/null 2>&1 || true
pkg_args=(); for p in $PUBLISHABLE; do pkg_args+=(-p "$p"); done
rustup run stable cargo package "${pkg_args[@]}" --allow-dirty 2>&1 | grep -E "Packaged|error"

# Honour CARGO_TARGET_DIR -- globbing a hard-coded `target/` silently reads
# whatever stale .crate files happen to be there when it is set, which is a
# gate that reports on the wrong artifact.
TARGET_DIR="${CARGO_TARGET_DIR:-$ROOT/target}"
PKG_DIR="${TARGET_DIR}/package"
shopt -s nullglob
crates=("${PKG_DIR}"/*.crate)
shopt -u nullglob
[ "${#crates[@]}" -gt 0 ] || { echo "FAIL: no .crate files in ${PKG_DIR}"; exit 1; }
echo "reading tarballs from ${PKG_DIR}"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
for c in "${crates[@]}"; do tar -xzf "$c" -C "$WORK"; done

fail=0
echo
for d in "$WORK"/*/; do
  pkg="$(basename "$d")"
  # Skip anything left over in target/package/ that is not a publishable crate
  # -- stale artifacts there would otherwise be silently graded as if they ship.
  name="$(awk -F'"' '/^name *=/ {print $2; exit}' "${d}Cargo.toml")"
  case " ${PUBLISHABLE} " in *" ${name} "*) ;; *) echo "skipping ${pkg} (not publishable)"; continue ;; esac
  # Grade only the CURRENT version. `target/package/` accumulates .crate files
  # across version bumps, and grading a stale one reports on an artifact that
  # will never be published -- a linq_rs_sql-0.3.0 tarball survived a bump back
  # to 0.2.0 and was still being built here. Same class as reading the repo when
  # the subject is the tarball (D-023).
  want_ver="$(cargo metadata --no-deps --format-version 1 \
    | python3 -c "import json,sys; p=[x for x in json.load(sys.stdin)['packages'] if x['name']=='${name}'][0]; print(p['version'])")"
  if [ "${pkg}" != "${name}-${want_ver}" ]; then
    echo "skipping ${pkg} (stale; ${name} is ${want_ver})"
    continue
  fi
  lock="${d}Cargo.lock"
  [ -f "$lock" ] || { echo "FAIL: ${pkg} ships no Cargo.lock"; fail=1; continue; }
  ver="$(awk -F'= *' '/^version *=/ {gsub(/[^0-9]/,"",$2); print $2; exit}' "$lock")"
  echo "=== ${pkg}: lockfile v${ver} ==="
  if [ "${ver:-99}" -gt "$MAX_LOCKFILE_VERSION" ]; then
    echo "FAIL: ${pkg} ships lockfile v${ver}; Cargo ${MSRV} cannot parse above v${MAX_LOCKFILE_VERSION}"
    fail=1
    continue
  fi

  # No crate here has a third-party dependency (D-032), so every tarball builds
  # fully offline; the guard below is what keeps that true.
  # The PROVIDER (D-031) depends on `linq_rs_sql` and a driver, so its tarball
  # cannot resolve offline until those are published. Point its sibling
  # dependency at the extracted sibling TARBALL -- not at the working tree, so
  # this still grades the packaged artifact -- and let the registry supply the
  # driver.
  # Every tarball must build fully OFFLINE, because D-032 permits no third-party
  # dependency anywhere: `linq_rs` has none and `linq_rs_sql` may have only
  # `linq_rs`. So a shipped manifest with a dependency is itself the failure --
  # this used to patch around it and resolve from the registry, which quietly
  # accommodated exactly what the rule forbids.
  #
  # Read from the TARBALL's manifest, and match `[dependencies.` with the dot:
  # `cargo package` NORMALISES a dependency to `[dependencies.name]`, never
  # `[dependencies]` + `name = ...`. An earlier version matched the repo's shape
  # and so silently never fired -- the same mistake D-023 exists to stop.
  if grep -qE '^\[dependencies\.' "${d}Cargo.toml"; then
    echo "FAIL: ${pkg}'s tarball declares a dependency:"
    grep -E '^\[dependencies\.' "${d}Cargo.toml" | sed 's/^/    /'
    echo "      D-032 permits none outside linq_rs_sql -> linq_rs."
    fail=1
    continue
  fi

  if (cd "$d" && rustup run "$MSRV_TC" cargo build --lib --offline 2>&1 | tail -3); then
    echo "  builds on ${MSRV_TC}"
  else
    echo "FAIL: ${pkg} does not build on ${MSRV_TC}"
    fail=1
  fi
done

echo
if [ "$fail" -ne 0 ]; then echo "MSRV tarball gate FAILED"; exit 1; fi
echo "PASS: every published tarball builds on ${MSRV_TC}"
