//! `FromRow` as generated by `entity!`. The unit tests in `src/from_row.rs`
//! cover resolution and decoding in isolation; these cover the macro path and
//! the properties a user depends on.
//!
//! The driver here is a hand-rolled mock, because the crate has zero
//! dependencies (D-024) and cannot dev-depend on rusqlite. The same design is
//! proven against a real SQLite separately — see `D-029`.

use linq_rs_sql::prelude::*;
use linq_rs_sql::{ColumnSet, FromRow, RowError, RowSource, SqlValueRef};

table! {
    emp (id) {
        id     -> Integer,
        name   -> Text,
        dept   -> Text,
        salary -> Integer,
        nick   -> Nullable<Text>,
        active -> Boolean,
    }
}

#[derive(Debug, PartialEq)]
pub struct Emp {
    pub id: i64,
    pub name: String,
    pub dept: String,
    pub salary: i64,
    pub nick: Option<String>,
    pub active: bool,
}

entity! {
    Emp => emp {
        id: Integer = id, name: Text = name, dept: Text = dept,
        salary: Integer = salary, nick: Nullable<Text> = nick, active: Boolean = active,
    }
}

/// A result set: column names plus one row of values, in the SAME order.
struct Mock<'a> {
    names: Vec<&'a str>,
    values: Vec<SqlValueRef<'a>>,
}

impl<'a> ColumnSet for Mock<'a> {
    fn column_count(&self) -> usize {
        self.names.len()
    }
    fn column_name_at(&self, at: usize) -> Option<&str> {
        self.names.get(at).copied()
    }
}

impl<'a> RowSource<'a> for Mock<'a> {
    fn value_at(&self, at: usize, _column: &'static str) -> Result<SqlValueRef<'a>, RowError> {
        Ok(self.values[at])
    }
}

fn int(n: i64) -> SqlValueRef<'static> {
    SqlValueRef::Integer(n)
}
fn txt(s: &str) -> SqlValueRef<'_> {
    SqlValueRef::Text(s)
}

/// The column list comes from `table!`, in declaration order.
#[test]
fn columns_are_taken_from_the_declaration() {
    assert_eq!(
        Emp::COLUMNS,
        &["id", "name", "dept", "salary", "nick", "active"]
    );
}

/// The property the whole design exists for: a result set whose column order
/// differs from the entity's declaration still materializes correctly. `SELECT *`
/// expands in table-declaration order, which the crate does not control and
/// which a migration can change under an already-compiled binary.
#[test]
fn a_reordered_result_set_still_materializes_correctly() {
    let row = Mock {
        names: vec!["dept", "active", "id", "nick", "salary", "name"],
        values: vec![
            txt("eng"),
            int(1),
            int(7),
            txt("A"),
            int(180_000),
            txt("Ada"),
        ],
    };
    let layout = Emp::resolve(&row).unwrap();
    assert!(
        !layout.is_identity(),
        "this result set is not in entity order"
    );
    assert_eq!(
        Emp::from_row(&row, &layout).unwrap(),
        Emp {
            id: 7,
            name: "Ada".into(),
            dept: "eng".into(),
            salary: 180_000,
            nick: Some("A".into()),
            active: true,
        }
    );
}

/// The positional decoder this design rejects would produce exactly this swap.
/// Here it must not.
#[test]
fn two_same_typed_adjacent_columns_do_not_swap() {
    let row = Mock {
        // `name` and `dept` exchanged; both TEXT, so no type check could fire.
        names: vec!["id", "dept", "name", "salary", "nick", "active"],
        values: vec![
            int(1),
            txt("eng"),
            txt("Ada"),
            int(1),
            SqlValueRef::Null,
            int(0),
        ],
    };
    let got = Emp::from_row(&row, &Emp::resolve(&row).unwrap()).unwrap();
    assert_eq!(got.name, "Ada", "name must not pick up dept's value");
    assert_eq!(got.dept, "eng");
}

#[test]
fn an_already_ordered_result_set_resolves_to_the_identity() {
    let row = Mock {
        names: vec!["id", "name", "dept", "salary", "nick", "active"],
        values: vec![
            int(1),
            txt("a"),
            txt("b"),
            int(2),
            SqlValueRef::Null,
            int(1),
        ],
    };
    assert!(Emp::resolve(&row).unwrap().is_identity());
}

#[test]
fn a_nullable_column_reads_null_as_none_and_a_value_as_some() {
    let names = vec!["id", "name", "dept", "salary", "nick", "active"];
    let absent = Mock {
        names: names.clone(),
        values: vec![
            int(1),
            txt("a"),
            txt("b"),
            int(2),
            SqlValueRef::Null,
            int(1),
        ],
    };
    assert_eq!(
        Emp::from_row(&absent, &Emp::resolve(&absent).unwrap())
            .unwrap()
            .nick,
        None
    );
    let present = Mock {
        names,
        values: vec![int(1), txt("a"), txt("b"), int(2), txt("z"), int(1)],
    };
    assert_eq!(
        Emp::from_row(&present, &Emp::resolve(&present).unwrap())
            .unwrap()
            .nick
            .as_deref(),
        Some("z")
    );
}

#[test]
fn a_null_in_a_non_nullable_column_names_it() {
    let row = Mock {
        names: vec!["id", "name", "dept", "salary", "nick", "active"],
        values: vec![
            int(1),
            SqlValueRef::Null,
            txt("b"),
            int(2),
            SqlValueRef::Null,
            int(1),
        ],
    };
    let e = Emp::from_row(&row, &Emp::resolve(&row).unwrap()).unwrap_err();
    assert_eq!(
        e.to_string(),
        "column `name` is NULL but is not declared Nullable<_>"
    );
}

/// D-029. `WHERE active = ?` bound `true` renders `active = 1`, so a database
/// keeps only 1. A reader that called 2 true would make one query value select
/// different rows in the two interpreters — verified doing exactly that against
/// real SQLite before this rule existed.
#[test]
fn an_integer_that_is_not_zero_or_one_is_not_a_bool() {
    for bad in [-1i64, 2, 100] {
        let row = Mock {
            names: vec!["id", "name", "dept", "salary", "nick", "active"],
            values: vec![
                int(1),
                txt("a"),
                txt("b"),
                int(2),
                SqlValueRef::Null,
                int(bad),
            ],
        };
        let e = Emp::from_row(&row, &Emp::resolve(&row).unwrap()).unwrap_err();
        assert!(
            matches!(e, RowError::OutOfRange { target: "bool", .. }),
            "active = {bad} must be refused, got: {e}"
        );
        assert_eq!(e.column(), Some("active"));
    }
}

/// A join produces two columns called `id`. Taking the first silently makes the
/// other table's data unreachable.
#[test]
fn a_duplicated_column_name_is_ambiguous() {
    let row = Mock {
        names: vec!["id", "name", "dept", "salary", "nick", "active", "id"],
        values: vec![
            int(1),
            txt("a"),
            txt("b"),
            int(2),
            SqlValueRef::Null,
            int(1),
            int(9),
        ],
    };
    let e = Emp::resolve(&row).unwrap_err();
    assert!(matches!(
        e,
        RowError::AmbiguousColumn {
            column: "id",
            at: (0, 6)
        }
    ));
}

/// Resolution takes no row, so a schema either matches or does not — the same
/// verdict whether or not any rows came back. This is why `ColumnSet` is a
/// separate trait.
#[test]
fn a_missing_column_fails_the_same_way_on_an_empty_result_set() {
    let names = vec!["id", "name"];
    let populated = Mock {
        names: names.clone(),
        values: vec![int(1), txt("a")],
    };
    let empty = Mock {
        names,
        values: vec![],
    };
    let a = Emp::resolve(&populated).unwrap_err().to_string();
    let b = Emp::resolve(&empty).unwrap_err().to_string();
    assert_eq!(a, b);
    assert_eq!(a, "no column `dept` in the result set (it has: id, name)");
}

#[test]
fn extra_columns_in_the_result_set_are_ignored() {
    let row = Mock {
        names: vec![
            "zzz", "id", "name", "dept", "aaa", "salary", "nick", "active",
        ],
        values: vec![
            int(0),
            int(5),
            txt("a"),
            txt("b"),
            int(0),
            int(3),
            SqlValueRef::Null,
            int(0),
        ],
    };
    let got = Emp::from_row(&row, &Emp::resolve(&row).unwrap()).unwrap();
    assert_eq!((got.id, got.salary), (5, 3));
}

/// A layout is tied to the shape it was resolved for, so it cannot be handed to
/// a different one. The `compile_fail` case below is the important half.
#[test]
fn a_layout_reports_its_arity() {
    let row = Mock {
        names: vec!["id", "name", "dept", "salary", "nick", "active"],
        values: vec![
            int(1),
            txt("a"),
            txt("b"),
            int(2),
            SqlValueRef::Null,
            int(1),
        ],
    };
    let l = Emp::resolve(&row).unwrap();
    assert_eq!(l.len(), 6);
    assert!(!l.is_empty());
}

/// `entity!`'s `no_from_row` arm, for a struct that cannot have a generated
/// `FromRow` — here because `extra` is not a column. Without the opt-out this
/// would be `E0063`.
#[test]
fn the_opt_out_arm_still_gives_the_readers() {
    table! { thing (id) { id -> Integer } }
    pub struct Thing {
        pub id: i64,
        #[allow(dead_code)]
        pub extra: String,
    }
    entity! { Thing => thing { id: Integer = id } no_from_row }

    let rows = vec![Thing {
        id: 3,
        extra: "not a column".into(),
    }];
    let q = linq_rs_sql::rows::query::<Thing>().filter(thing::id.gt(1i64));
    assert_eq!(q.to_sql().sql, "SELECT * FROM thing WHERE (id > ?)");
    assert_eq!(q.to_memory(&rows).map(|t| t.id).collect::<Vec<_>>(), [3]);
}
