//! `FromRow` as generated by `entity!`. The unit tests in `src/from_row.rs`
//! cover resolution and decoding in isolation; these cover the macro path and
//! the properties a user depends on.
//!
//! The driver here is a hand-rolled mock, because the crate has zero
//! dependencies (D-024) and cannot dev-depend on rusqlite. The same design is
//! proven against a real SQLite separately — see `D-029`.

use linq_rs_sql::prelude::*;
use linq_rs_sql::{ColumnSet, FromRow, RowError, RowSource, SqlValueRef};

table! {
    emp (id) {
        id     -> Integer,
        name   -> Text,
        dept   -> Text,
        salary -> Integer,
        nick   -> Nullable<Text>,
        active -> Boolean,
    }
}

#[derive(Debug, PartialEq)]
pub struct Emp {
    pub id: i64,
    pub name: String,
    pub dept: String,
    pub salary: i64,
    pub nick: Option<String>,
    pub active: bool,
}

entity! {
    Emp => emp {
        id: Integer = id, name: Text = name, dept: Text = dept,
        salary: Integer = salary, nick: Nullable<Text> = nick, active: Boolean = active,
    }
}

/// A result set: column names plus one row of values, in the SAME order.
struct Mock<'a> {
    names: Vec<&'a str>,
    values: Vec<SqlValueRef<'a>>,
}

impl<'a> ColumnSet for Mock<'a> {
    fn column_count(&self) -> usize {
        self.names.len()
    }
    fn column_name_at(&self, at: usize) -> Option<&str> {
        self.names.get(at).copied()
    }
}

impl<'a> RowSource<'a> for Mock<'a> {
    fn value_at(&self, at: usize, _column: &'static str) -> Result<SqlValueRef<'a>, RowError> {
        Ok(self.values[at])
    }
}

fn int(n: i64) -> SqlValueRef<'static> {
    SqlValueRef::Integer(n)
}
fn txt(s: &str) -> SqlValueRef<'_> {
    SqlValueRef::Text(s)
}

/// The column list comes from `table!`, in declaration order.
#[test]
fn columns_are_taken_from_the_declaration() {
    assert_eq!(
        Emp::COLUMNS,
        &["id", "name", "dept", "salary", "nick", "active"]
    );
}

/// The property the whole design exists for: a result set whose column order
/// differs from the entity's declaration still materializes correctly. `SELECT *`
/// expands in table-declaration order, which the crate does not control and
/// which a migration can change under an already-compiled binary.
#[test]
fn a_reordered_result_set_still_materializes_correctly() {
    let row = Mock {
        names: vec!["dept", "active", "id", "nick", "salary", "name"],
        values: vec![
            txt("eng"),
            int(1),
            int(7),
            txt("A"),
            int(180_000),
            txt("Ada"),
        ],
    };
    let layout = Emp::resolve(&row).unwrap();
    assert!(
        !layout.is_identity(),
        "this result set is not in entity order"
    );
    assert_eq!(
        Emp::from_row(&row, &layout).unwrap(),
        Emp {
            id: 7,
            name: "Ada".into(),
            dept: "eng".into(),
            salary: 180_000,
            nick: Some("A".into()),
            active: true,
        }
    );
}

/// The positional decoder this design rejects would produce exactly this swap.
/// Here it must not.
#[test]
fn two_same_typed_adjacent_columns_do_not_swap() {
    let row = Mock {
        // `name` and `dept` exchanged; both TEXT, so no type check could fire.
        names: vec!["id", "dept", "name", "salary", "nick", "active"],
        values: vec![
            int(1),
            txt("eng"),
            txt("Ada"),
            int(1),
            SqlValueRef::Null,
            int(0),
        ],
    };
    let got = Emp::from_row(&row, &Emp::resolve(&row).unwrap()).unwrap();
    assert_eq!(got.name, "Ada", "name must not pick up dept's value");
    assert_eq!(got.dept, "eng");
}

#[test]
fn an_already_ordered_result_set_resolves_to_the_identity() {
    let row = Mock {
        names: vec!["id", "name", "dept", "salary", "nick", "active"],
        values: vec![
            int(1),
            txt("a"),
            txt("b"),
            int(2),
            SqlValueRef::Null,
            int(1),
        ],
    };
    assert!(Emp::resolve(&row).unwrap().is_identity());
}

#[test]
fn a_nullable_column_reads_null_as_none_and_a_value_as_some() {
    let names = vec!["id", "name", "dept", "salary", "nick", "active"];
    let absent = Mock {
        names: names.clone(),
        values: vec![
            int(1),
            txt("a"),
            txt("b"),
            int(2),
            SqlValueRef::Null,
            int(1),
        ],
    };
    assert_eq!(
        Emp::from_row(&absent, &Emp::resolve(&absent).unwrap())
            .unwrap()
            .nick,
        None
    );
    let present = Mock {
        names,
        values: vec![int(1), txt("a"), txt("b"), int(2), txt("z"), int(1)],
    };
    assert_eq!(
        Emp::from_row(&present, &Emp::resolve(&present).unwrap())
            .unwrap()
            .nick
            .as_deref(),
        Some("z")
    );
}

#[test]
fn a_null_in_a_non_nullable_column_names_it() {
    let row = Mock {
        names: vec!["id", "name", "dept", "salary", "nick", "active"],
        values: vec![
            int(1),
            SqlValueRef::Null,
            txt("b"),
            int(2),
            SqlValueRef::Null,
            int(1),
        ],
    };
    let e = Emp::from_row(&row, &Emp::resolve(&row).unwrap()).unwrap_err();
    assert_eq!(
        e.to_string(),
        "column `name` is NULL but is not declared Nullable<_>"
    );
}

/// D-029. `WHERE active = ?` bound `true` renders `active = 1`, so a database
/// keeps only 1. A reader that called 2 true would make one query value select
/// different rows in the two interpreters — verified doing exactly that against
/// real SQLite before this rule existed.
#[test]
fn an_integer_that_is_not_zero_or_one_is_not_a_bool() {
    for bad in [-1i64, 2, 100] {
        let row = Mock {
            names: vec!["id", "name", "dept", "salary", "nick", "active"],
            values: vec![
                int(1),
                txt("a"),
                txt("b"),
                int(2),
                SqlValueRef::Null,
                int(bad),
            ],
        };
        let e = Emp::from_row(&row, &Emp::resolve(&row).unwrap()).unwrap_err();
        assert!(
            matches!(e, RowError::OutOfRange { target: "bool", .. }),
            "active = {bad} must be refused, got: {e}"
        );
        assert_eq!(e.column(), Some("active"));
    }
}

/// A join produces two columns called `id`. Taking the first silently makes the
/// other table's data unreachable.
#[test]
fn a_duplicated_column_name_is_ambiguous() {
    let row = Mock {
        names: vec!["id", "name", "dept", "salary", "nick", "active", "id"],
        values: vec![
            int(1),
            txt("a"),
            txt("b"),
            int(2),
            SqlValueRef::Null,
            int(1),
            int(9),
        ],
    };
    let e = Emp::resolve(&row).unwrap_err();
    assert!(matches!(
        e,
        RowError::AmbiguousColumn {
            column: "id",
            at: (0, 6)
        }
    ));
}

/// Resolution takes no row, so a schema either matches or does not — the same
/// verdict whether or not any rows came back. This is why `ColumnSet` is a
/// separate trait.
#[test]
fn a_missing_column_fails_the_same_way_on_an_empty_result_set() {
    let names = vec!["id", "name"];
    let populated = Mock {
        names: names.clone(),
        values: vec![int(1), txt("a")],
    };
    let empty = Mock {
        names,
        values: vec![],
    };
    let a = Emp::resolve(&populated).unwrap_err().to_string();
    let b = Emp::resolve(&empty).unwrap_err().to_string();
    assert_eq!(a, b);
    assert_eq!(a, "no column `dept` in the result set (it has: id, name)");
}

#[test]
fn extra_columns_in_the_result_set_are_ignored() {
    let row = Mock {
        names: vec![
            "zzz", "id", "name", "dept", "aaa", "salary", "nick", "active",
        ],
        values: vec![
            int(0),
            int(5),
            txt("a"),
            txt("b"),
            int(0),
            int(3),
            SqlValueRef::Null,
            int(0),
        ],
    };
    let got = Emp::from_row(&row, &Emp::resolve(&row).unwrap()).unwrap();
    assert_eq!((got.id, got.salary), (5, 3));
}

/// A layout is tied to the shape it was resolved for, so it cannot be handed to
/// a different one — `Layout<R>` holds `PhantomData<fn() -> R>`, so the type
/// system refuses the mix-up.
///
/// This comment used to promise "the `compile_fail` case below is the important
/// half". There was no such case below, and there could not be: doctests in
/// `tests/` are never compiled or run by cargo, so a `compile_fail` block here
/// would be inert text. The enforced cases live in `src/` — see the five
/// `compile_fail` doctests there, and `seam-tests/src/lib.rs` for the `D-102`
/// pair.
#[test]
fn a_layout_reports_its_arity() {
    let row = Mock {
        names: vec!["id", "name", "dept", "salary", "nick", "active"],
        values: vec![
            int(1),
            txt("a"),
            txt("b"),
            int(2),
            SqlValueRef::Null,
            int(1),
        ],
    };
    let l = Emp::resolve(&row).unwrap();
    assert_eq!(l.len(), 6);
    assert!(!l.is_empty());
}

/// `entity!`'s `no_from_row` arm, for a struct that cannot have a generated
/// `FromRow` — here because `extra` is not a column. Without the opt-out this
/// would be `E0063`.
#[test]
fn the_opt_out_arm_still_gives_the_readers() {
    table! { thing (id) { id -> Integer } }
    pub struct Thing {
        pub id: i64,
        #[allow(dead_code)]
        pub extra: String,
    }
    entity! { Thing => thing { id: Integer = id } no_from_row }

    let rows = vec![Thing {
        id: 3,
        extra: "not a column".into(),
    }];
    let q = linq_rs_sql::rows::query::<Thing>().filter(thing::id.gt(1i64));
    assert_eq!(q.to_sql().sql, "SELECT id FROM thing WHERE (id > ?)");
    assert_eq!(q.to_memory(&rows).map(|t| t.id).collect::<Vec<_>>(), [3]);
}

/// D-030. `to_sql()` now names the columns, so a result set produced by this
/// crate's own SQL arrives in the entity's declared order and resolution is
/// provably the identity permutation. By-name reading then costs nothing and
/// still covers the cases the crate does *not* control: a hand-written query, a
/// join, a view, a driver that reorders.
///
/// This is the defence-in-depth half. The reordered-result-set test above is the
/// half that matters when something else chose the order.
#[test]
fn a_query_this_crate_generated_resolves_to_the_identity() {
    // Model a result set shaped by `to_sql()`: the entity's own column list.
    use linq_rs_sql::rows::Entity;
    let names: Vec<&str> = <Emp as Entity>::ALL_COLUMNS.to_vec();
    assert_eq!(
        names,
        Emp::COLUMNS,
        "the projected SELECT list and the read list must be the same columns"
    );
    let row = Mock {
        names,
        values: vec![
            int(1),
            txt("a"),
            txt("b"),
            int(2),
            SqlValueRef::Null,
            int(1),
        ],
    };
    let layout = Emp::resolve(&row).unwrap();
    assert!(
        layout.is_identity(),
        "a query we generated must not need reordering"
    );
}

/// The lower-level `Query` builder has no `Entity`, so it keeps emitting `*` —
/// there is no declared column list for it to name. Worth pinning so the
/// inconsistency is deliberate rather than discovered.
#[test]
fn the_entity_free_query_builder_still_emits_star() {
    assert_eq!(
        emp::table().filter(emp::id.gt(1i64)).to_sql().sql,
        "SELECT * FROM emp WHERE (id > ?)"
    );
}

/// Resolution and field decoding, exercised one unit at a time.
///
/// These 17 tests lived in `src/from_row.rs` behind `#[cfg(test)] mod tests`
/// until 2026-09-29. That placement earns its keep when tests need *private*
/// items, and these need none: every name below is `pub` and re-exported from
/// `lib.rs`. It was the only file in either crate doing it, and it made 24% of
/// `from_row.rs` test code. Moved verbatim -- same names, same assertions.
///
/// Kept as a module so `Cols` and `WANT` stay scoped and cannot collide with the
/// `Mock` helper the tests above use.
mod resolution {
    use linq_rs_sql::{
        resolve_by_name, Boolean, ColumnSet, Float, Integer, Layout, LoadField, Nullable, RowError,
        SqlValueRef, Text,
    };

    struct Cols(Vec<&'static str>);
    impl ColumnSet for Cols {
        fn column_count(&self) -> usize {
            self.0.len()
        }
        fn column_name_at(&self, at: usize) -> Option<&str> {
            self.0.get(at).copied()
        }
    }

    const WANT: &[&str] = &["id", "name", "dept"];

    #[test]
    fn resolves_by_name_regardless_of_position() {
        let l: Layout<()> = resolve_by_name(&Cols(vec!["dept", "id", "name"]), WANT).unwrap();
        assert_eq!(
            (l.position(0), l.position(1), l.position(2)),
            (1, 2, 0),
            "id, name, dept live at 1, 2, 0"
        );
        assert!(!l.is_identity());
    }

    #[test]
    fn an_already_ordered_result_set_is_the_identity() {
        let l: Layout<()> = resolve_by_name(&Cols(vec!["id", "name", "dept"]), WANT).unwrap();
        assert!(l.is_identity());
    }

    #[test]
    fn extra_columns_are_ignored() {
        let l: Layout<()> =
            resolve_by_name(&Cols(vec!["x", "id", "y", "name", "dept", "z"]), WANT).unwrap();
        assert_eq!((l.position(0), l.position(1), l.position(2)), (1, 3, 4));
    }

    #[test]
    fn a_missing_column_names_itself_and_what_was_available() {
        let e = resolve_by_name::<(), _>(&Cols(vec!["id", "name"]), WANT).unwrap_err();
        assert!(matches!(e, RowError::NoSuchColumn { column: "dept", .. }));
        assert_eq!(
            e.to_string(),
            "no column `dept` in the result set (it has: id, name)"
        );
    }

    /// An empty result set must fail exactly like a populated one. This is why
    /// `ColumnSet` is separate from `RowSource`: resolution takes no row, so a
    /// schema either matches or does not, regardless of how much data came back.
    #[test]
    fn resolution_does_not_depend_on_there_being_rows() {
        let empty = resolve_by_name::<(), _>(&Cols(vec!["id", "name"]), WANT).unwrap_err();
        assert_eq!(empty.to_string(), {
            let same = resolve_by_name::<(), _>(&Cols(vec!["id", "name"]), WANT).unwrap_err();
            same.to_string()
        });
    }

    /// `SELECT * FROM a JOIN b` yields two `id` columns. Taking the first makes
    /// the second table's data unreachable with nothing saying so.
    #[test]
    fn a_duplicated_name_is_ambiguous_not_first_wins() {
        let e =
            resolve_by_name::<(), _>(&Cols(vec!["id", "name", "dept", "id"]), WANT).unwrap_err();
        assert!(matches!(
            e,
            RowError::AmbiguousColumn {
                column: "id",
                at: (0, 3)
            }
        ));
        assert!(e.to_string().contains("appears more than once"));
    }

    #[test]
    fn name_matching_is_case_sensitive_and_owned_by_this_crate() {
        // rusqlite folds ASCII case; a strict adapter does not. Leaving the rule
        // to the adapter gave two verdicts for one schema, so the rule is here.
        let e = resolve_by_name::<(), _>(&Cols(vec!["ID", "NAME", "DEPT"]), WANT).unwrap_err();
        assert!(matches!(e, RowError::NoSuchColumn { column: "id", .. }));
    }

    // ── decoding ───────────────────────────────────────────────────────────

    #[test]
    fn null_into_a_non_nullable_column_is_an_error_naming_it() {
        let e = <Integer as LoadField<'_, i64>>::load_field(SqlValueRef::Null, "id").unwrap_err();
        assert_eq!(
            e.to_string(),
            "column `id` is NULL but is not declared Nullable<_>"
        );
    }

    #[test]
    fn null_into_a_nullable_column_is_none() {
        let got = <Nullable<Text> as LoadField<'_, Option<String>>>::load_field(
            SqlValueRef::Null,
            "nick",
        )
        .unwrap();
        assert_eq!(got, None);
    }

    #[test]
    fn a_present_nullable_value_is_some() {
        let got = <Nullable<Text> as LoadField<'_, Option<String>>>::load_field(
            SqlValueRef::Text("ann"),
            "nick",
        )
        .unwrap();
        assert_eq!(got.as_deref(), Some("ann"));
    }

    #[test]
    fn a_wrong_shape_names_the_column_the_declared_type_and_what_arrived() {
        let e = <Integer as LoadField<'_, i64>>::load_field(SqlValueRef::Text("nope"), "n")
            .unwrap_err();
        assert_eq!(
            e.to_string(),
            "column `n` is declared INTEGER but the driver returned Text"
        );
    }

    #[test]
    fn narrowing_is_checked_never_cast() {
        assert_eq!(
            <Integer as LoadField<'_, i64>>::load_field(SqlValueRef::Integer(i64::MAX), "n")
                .unwrap(),
            i64::MAX
        );
        let e =
            <Integer as LoadField<'_, i32>>::load_field(SqlValueRef::Integer(5_000_000_000), "n")
                .unwrap_err();
        assert_eq!(
            e.to_string(),
            "column `n`: Integer(5000000000) does not fit `i32`"
        );
    }

    /// D-029, and the reason this module refuses a coercion that every other
    /// SQLite binding performs. `WHERE active = ?` bound `true` renders
    /// `active = 1`, so the database keeps only 1. A reader that called 2 true
    /// would make the same query value select different rows in the two
    /// interpreters.
    #[test]
    fn bool_accepts_only_zero_and_one() {
        assert!(
            !<Boolean as LoadField<'_, bool>>::load_field(SqlValueRef::Integer(0), "a").unwrap()
        );
        assert!(
            <Boolean as LoadField<'_, bool>>::load_field(SqlValueRef::Integer(1), "a").unwrap()
        );
        for bad in [-1i64, 2, i64::MAX] {
            let e = <Boolean as LoadField<'_, bool>>::load_field(SqlValueRef::Integer(bad), "a")
                .unwrap_err();
            assert!(
                matches!(e, RowError::OutOfRange { target: "bool", .. }),
                "{bad} must not become a bool, got {e}"
            );
        }
    }

    #[test]
    fn text_can_borrow_from_the_row_buffer() {
        let owned = String::from("borrowed");
        let got =
            <Text as LoadField<'_, &str>>::load_field(SqlValueRef::Text(&owned), "s").unwrap();
        assert_eq!(got, "borrowed");
        assert!(std::ptr::eq(got.as_ptr(), owned.as_ptr()), "no copy");
    }

    #[test]
    fn an_integer_widens_into_a_declared_real_but_only_losslessly() {
        assert_eq!(
            <Float as LoadField<'_, f64>>::load_field(SqlValueRef::Integer(3), "r").unwrap(),
            3.0
        );
        let e =
            <Float as LoadField<'_, f64>>::load_field(SqlValueRef::Integer((1i64 << 53) + 1), "r")
                .unwrap_err();
        assert!(matches!(e, RowError::OutOfRange { target: "f64", .. }));
    }

    #[test]
    fn a_row_ordinal_can_be_attached_and_is_not_overwritten() {
        let e = <Integer as LoadField<'_, i64>>::load_field(SqlValueRef::Null, "id")
            .unwrap_err()
            .at_row(99);
        assert_eq!(
            e.to_string(),
            "column `id` is NULL but is not declared Nullable<_> (row 99)"
        );
        let again = e.at_row(1);
        assert!(again.to_string().contains("(row 99)"), "first wins");
    }

    #[test]
    fn every_naming_variant_reports_its_column() {
        let cases: Vec<RowError> = vec![
            resolve_by_name::<(), _>(&Cols(vec![]), &["id"]).unwrap_err(),
            <Integer as LoadField<'_, i64>>::load_field(SqlValueRef::Null, "id").unwrap_err(),
            <Integer as LoadField<'_, i64>>::load_field(SqlValueRef::Text("x"), "id").unwrap_err(),
        ];
        for e in cases {
            assert_eq!(e.column(), Some("id"), "{e}");
        }
    }
}
