//! [`Column`] trait + per-SQL-type operator extension traits.
//!
//! Operators are grouped by which `SqlType` they apply to:
//!
//! - [`ExprExt`]  — universal: `.eq`, `.ne`, `.is_null`
//! - [`IntOps`]   — `Integer`: `.lt`, `.lte`, `.gt`, `.gte`
//! - [`FloatOps`] — `Float`:   `.lt`, `.lte`, `.gt`, `.gte`
//! - [`TextOps`]  — `Text`:    `.lt`, `.lte`, `.gt`, `.gte`, `.like`
//! - [`BoolOps`]  — `Boolean`: `.and`, `.or`
//! - free function [`crate::not`] — `Boolean`: `NOT expr`
//!
//! All extension traits have blanket impls keyed on `Expr<SqlType = ...>`,
//! so column types, primitive literals, and intermediate expression nodes
//! all pick up the same operators automatically.

use crate::expr::{And, Eq, Expr, Gt, GtEq, IsNotNull, IsNull, Like, Lt, LtEq, NotEq, Or};
use crate::types::{Boolean, CompareWith, Family, Float, Integer, LogicWith, Text};

/// A SQL column. The zero-sized types generated by [`crate::table!`]
/// implement this trait.
///
/// Implementors must also implement [`Expr`] — that's where the column
/// declares its SQL type (`Integer`, `Text`, …) and how it writes itself
/// (`sql.push_str(C::NAME)`).
pub trait Column: Expr + Sized {
    /// The table marker type this column belongs to. Used by
    /// [`Selection`](crate::Selection) to ensure all selected columns come from
    /// the same table.
    type Table;
    /// The SQL identifier (column name) for this column.
    const NAME: &'static str;
}

// ═══════════════════════════════════════════════════════════════════════════
// Universal: ExprExt
// ═══════════════════════════════════════════════════════════════════════════

/// Equality and NULL-test operators applicable to expressions of any
/// `SqlType`. Blanket-implemented for every `Expr + Sized`.
pub trait ExprExt: Expr + Sized {
    /// `self = rhs`. RHS must be in the same *family* as `self` — either side
    /// may be nullable, and if either is, the result is `Nullable<Boolean>`.
    fn eq<R>(self, rhs: R) -> Eq<Self, R>
    where
        R: Expr,
        Self::SqlType: CompareWith<R::SqlType>,
    {
        Eq {
            left: self,
            right: rhs,
        }
    }

    /// `self != rhs`.
    fn ne<R>(self, rhs: R) -> NotEq<Self, R>
    where
        R: Expr,
        Self::SqlType: CompareWith<R::SqlType>,
    {
        NotEq {
            left: self,
            right: rhs,
        }
    }

    /// `self IS NULL`.
    ///
    /// Consumes `self` like every other builder method here; clippy's
    /// `wrong_self_convention` lint expects `is_*` methods to take `&self`
    /// or `&mut self`, but the consumer-of-self convention is consistent
    /// across this trait.
    #[allow(clippy::wrong_self_convention)]
    fn is_null(self) -> IsNull<Self> {
        IsNull { inner: self }
    }

    /// `self IS NOT NULL`.
    #[allow(clippy::wrong_self_convention)]
    fn is_not_null(self) -> IsNotNull<Self> {
        IsNotNull { inner: self }
    }
}

impl<E: Expr + Sized> ExprExt for E {}

// ═══════════════════════════════════════════════════════════════════════════
// IntOps — ordering on Integer
// ═══════════════════════════════════════════════════════════════════════════

/// Ordering operators for `Integer` expressions.
pub trait IntOps: Expr + Sized
where
    Self::SqlType: Family<Base = Integer>,
{
    /// `self < rhs`.
    fn lt<R>(self, rhs: R) -> Lt<Self, R>
    where
        R: Expr,
        R::SqlType: Family<Base = Integer>,
        Self::SqlType: CompareWith<R::SqlType>,
    {
        Lt {
            left: self,
            right: rhs,
        }
    }
    /// `self <= rhs`.
    fn lte<R>(self, rhs: R) -> LtEq<Self, R>
    where
        R: Expr,
        R::SqlType: Family<Base = Integer>,
        Self::SqlType: CompareWith<R::SqlType>,
    {
        LtEq {
            left: self,
            right: rhs,
        }
    }
    /// `self > rhs`.
    fn gt<R>(self, rhs: R) -> Gt<Self, R>
    where
        R: Expr,
        R::SqlType: Family<Base = Integer>,
        Self::SqlType: CompareWith<R::SqlType>,
    {
        Gt {
            left: self,
            right: rhs,
        }
    }
    /// `self >= rhs`.
    fn gte<R>(self, rhs: R) -> GtEq<Self, R>
    where
        R: Expr,
        R::SqlType: Family<Base = Integer>,
        Self::SqlType: CompareWith<R::SqlType>,
    {
        GtEq {
            left: self,
            right: rhs,
        }
    }
}
impl<E> IntOps for E
where
    E: Expr + Sized,
    E::SqlType: Family<Base = Integer>,
{
}

// ═══════════════════════════════════════════════════════════════════════════
// FloatOps — ordering on Float
// ═══════════════════════════════════════════════════════════════════════════

/// Ordering operators for `Float` expressions.
pub trait FloatOps: Expr + Sized
where
    Self::SqlType: Family<Base = Float>,
{
    /// `self < rhs`.
    fn lt<R>(self, rhs: R) -> Lt<Self, R>
    where
        R: Expr,
        R::SqlType: Family<Base = Float>,
        Self::SqlType: CompareWith<R::SqlType>,
    {
        Lt {
            left: self,
            right: rhs,
        }
    }
    /// `self <= rhs`.
    fn lte<R>(self, rhs: R) -> LtEq<Self, R>
    where
        R: Expr,
        R::SqlType: Family<Base = Float>,
        Self::SqlType: CompareWith<R::SqlType>,
    {
        LtEq {
            left: self,
            right: rhs,
        }
    }
    /// `self > rhs`.
    fn gt<R>(self, rhs: R) -> Gt<Self, R>
    where
        R: Expr,
        R::SqlType: Family<Base = Float>,
        Self::SqlType: CompareWith<R::SqlType>,
    {
        Gt {
            left: self,
            right: rhs,
        }
    }
    /// `self >= rhs`.
    fn gte<R>(self, rhs: R) -> GtEq<Self, R>
    where
        R: Expr,
        R::SqlType: Family<Base = Float>,
        Self::SqlType: CompareWith<R::SqlType>,
    {
        GtEq {
            left: self,
            right: rhs,
        }
    }
}
impl<E> FloatOps for E
where
    E: Expr + Sized,
    E::SqlType: Family<Base = Float>,
{
}

// ═══════════════════════════════════════════════════════════════════════════
// TextOps — lexicographic ordering + LIKE
// ═══════════════════════════════════════════════════════════════════════════

/// Text-specific operators: lexicographic comparison and `LIKE`.
pub trait TextOps: Expr + Sized
where
    Self::SqlType: Family<Base = Text>,
{
    /// `self < rhs` — lexicographic.
    fn lt<R>(self, rhs: R) -> Lt<Self, R>
    where
        R: Expr,
        R::SqlType: Family<Base = Text>,
        Self::SqlType: CompareWith<R::SqlType>,
    {
        Lt {
            left: self,
            right: rhs,
        }
    }
    /// `self <= rhs` — lexicographic.
    fn lte<R>(self, rhs: R) -> LtEq<Self, R>
    where
        R: Expr,
        R::SqlType: Family<Base = Text>,
        Self::SqlType: CompareWith<R::SqlType>,
    {
        LtEq {
            left: self,
            right: rhs,
        }
    }
    /// `self > rhs` — lexicographic.
    fn gt<R>(self, rhs: R) -> Gt<Self, R>
    where
        R: Expr,
        R::SqlType: Family<Base = Text>,
        Self::SqlType: CompareWith<R::SqlType>,
    {
        Gt {
            left: self,
            right: rhs,
        }
    }
    /// `self >= rhs` — lexicographic.
    fn gte<R>(self, rhs: R) -> GtEq<Self, R>
    where
        R: Expr,
        R::SqlType: Family<Base = Text>,
        Self::SqlType: CompareWith<R::SqlType>,
    {
        GtEq {
            left: self,
            right: rhs,
        }
    }
    /// `self LIKE pattern` — SQL `%`/`_` glob match.
    fn like<R>(self, pattern: R) -> Like<Self, R>
    where
        R: Expr,
        R::SqlType: Family<Base = Text>,
        Self::SqlType: CompareWith<R::SqlType>,
    {
        Like {
            left: self,
            right: pattern,
        }
    }
}
impl<E> TextOps for E
where
    E: Expr + Sized,
    E::SqlType: Family<Base = Text>,
{
}

// ═══════════════════════════════════════════════════════════════════════════
// BoolOps — logical AND / OR
// ═══════════════════════════════════════════════════════════════════════════

/// Logical AND / OR for `Boolean` expressions. (NOT lives at the module
/// level as the free function [`crate::not`].)
pub trait BoolOps: Expr + Sized
where
    Self::SqlType: Family<Base = Boolean>,
{
    /// `self AND rhs`.
    fn and<R>(self, rhs: R) -> And<Self, R>
    where
        R: Expr,
        R::SqlType: Family<Base = Boolean>,
        Self::SqlType: LogicWith<R::SqlType>,
    {
        And {
            left: self,
            right: rhs,
        }
    }
    /// `self OR rhs`.
    fn or<R>(self, rhs: R) -> Or<Self, R>
    where
        R: Expr,
        R::SqlType: Family<Base = Boolean>,
        Self::SqlType: LogicWith<R::SqlType>,
    {
        Or {
            left: self,
            right: rhs,
        }
    }
}
impl<E> BoolOps for E
where
    E: Expr + Sized,
    E::SqlType: Family<Base = Boolean>,
{
}
